# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                     Defaults Configuration                  ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

$filemanager = dolphin --platformtheme kde 
#$browser = cachy-browser
$browser = firefox
#$applauncher = rofi -show combi -modi window,run,combi -combi-modi window,run
#$applauncher = rofi -show drun
$applauncher = rofi -show drun -theme ~/.config/rofi/launchers/type-3/style-5.rasi
$terminal = kitty
$idlehandler = swayidle -w timeout 300 'swaylock -f -c 000000' before-sleep 'swaylock -f -c 000000'
$capturing = grim -g "$(slurp)" - | swappy -f -
$power = ~/.config/rofi/powermenu/type-2/powermenu.sh


$clip = rofi -modi clipboard:~/.local/bin/cliphist-rofi-img -show clipboard -show-icons -theme ~/.config/rofi/launchers/type-3/clipboard.rasi


$pdfviewer = okular --platformtheme kde
